/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

/**
 *
 * @author jackdaniel
 */
public class paymentForm extends javax.swing.JFrame {
    String finalTotal, finalUid, finalWeight;
    int finalSid;
    // Constructor that accepts the total amount
   public paymentForm(String total, String uid, int sid, String weight) {
      initComponents();
    
    this.finalTotal = total;
    this.finalUid = uid;
    this.finalSid = sid;
    this.finalWeight = weight;

    totalamount.setText(total);
    totalamount.setEditable(false);
    
    // AUTO-FILL DATE HERE
    java.time.LocalDate today = java.time.LocalDate.now();
    jTextField1.setText(today.toString()); // jTextField1 is your Date field
    jTextField1.setEditable(false); // Optional: makes it read-only
    
    paymentmethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "GCash", "Maya" }));
    }

    /**
     * Creates new form paymentForm
     */
    public paymentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        totalamount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cashreceived = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        change = new javax.swing.JTextField();
        paymentmethod = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/adminlogo.png"))); // NOI18N
        jLabel6.setText("jLabel3");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 113, 100));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("PAYMENT FORM");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 310, -1));

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 100));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel1.setText("PAYMENT METHOD:");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 220, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel3.setText("TOTAL AMOUNT:");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel7.add(totalamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 260, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel4.setText("CASH RECEIVED:");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        cashreceived.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cashreceivedKeyReleased(evt);
            }
        });
        jPanel7.add(cashreceived, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 260, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel5.setText("DATE:");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        jPanel7.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 260, 50));

        paymentmethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel7.add(paymentmethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 330, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel8.setText("CHANGE:");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel7.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 260, 50));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 580, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       transactionform tf = new transactionform();
       tf.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String cash = cashreceived.getText().trim();
    String method = paymentmethod.getSelectedItem().toString();
    String date = jTextField1.getText(); 

    if (cash.isEmpty() || change.getText().equals("Insufficient Cash") || change.getText().equals("0.00")) {
        javax.swing.JOptionPane.showMessageDialog(null, "Please enter a valid cash amount!");
        return;
    }

    try {
        java.sql.Connection conn = config.config.connectDB();
        String sql = "INSERT INTO tbl_laundryorders (u_id, s_id, t_weight, t_total, t_method, t_status, t_date) VALUES (?, ?, ?, ?, ?, ?, ?)";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, finalUid);
        pst.setInt(2, finalSid);
        pst.setString(3, finalWeight);
        pst.setString(4, finalTotal);
        pst.setString(5, method);
        pst.setString(6, "Pending"); 
        pst.setString(7, date); 

        pst.executeUpdate();
        
        javax.swing.JOptionPane.showMessageDialog(null, "Payment Successful! Generating Receipt...");

        // --- RECEIPT GENERATION START ---
        receiptForm rf = new receiptForm();
        
        // Constructing the receipt string
        String receiptText = 
            "*******************************************\n" +
            "       CLOTHING LAUNDRY SERVICES           \n" +
            "           CEBU CITY BRANCH                \n" +
            "*******************************************\n\n" +
            " Date:      " + date + "\n" +
            " Customer:  ID #" + finalUid + "\n" +
            " Method:    " + method + "\n" +
            "-------------------------------------------\n" +
            " Weight:    " + finalWeight + " kg\n" +
            " Total:     ₱ " + finalTotal + "\n" +
            " Cash:      ₱ " + cash + "\n" +
            " Change:    ₱ " + change.getText() + "\n" +
            "-------------------------------------------\n" +
            " Status:    PENDING\n\n" +
            "*******************************************\n" +
            "      PLEASE KEEP THIS FOR YOUR CLAIM      \n" +
            "*******************************************";

        // Send the text to the receiptArea in receiptForm
        rf.receiptArea.setText(receiptText); 
        rf.receiptArea.setEditable(false);
        
        // Show the receipt form and close this payment form
        rf.setVisible(true);
        this.dispose();
        // --- RECEIPT GENERATION END ---

    } catch (java.sql.SQLException e) {
        System.out.println("Database Error: " + e.getMessage());
        javax.swing.JOptionPane.showMessageDialog(null, "Transaction Failed.");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cashreceivedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashreceivedKeyReleased
        try {
        double total = Double.parseDouble(totalamount.getText());
        double cash = Double.parseDouble(cashreceived.getText());
        
        if (cash >= total) {
            double changeAmount = cash - total;
            change.setText(String.format("%.2f", changeAmount));
        } else {
            change.setText("Insufficient Cash");
        }
    } catch (NumberFormatException nfe) {
        change.setText("0.00");
    }
    }//GEN-LAST:event_cashreceivedKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paymentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cashreceived;
    private javax.swing.JTextField change;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> paymentmethod;
    private javax.swing.JTextField totalamount;
    // End of variables declaration//GEN-END:variables
}
