/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;
import config.config;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import config.session;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import main.login;

/**
 *
 * @author jackdaniel
 */
public class transactionform extends javax.swing.JFrame {

    /**
     * Creates new form transactionform
     */
    public transactionform() {
         // 1. Validate FIRST. If uid is 0, stop everything immediately.
    if (session.uid == 0) {
        JOptionPane.showMessageDialog(null, "Login First!");
        login log = new login();
        log.setVisible(true);
        this.dispose(); 
        return; // This prevents initComponents() from ever running
    }
        initComponents();
        updateServiceList(); // Add this line here
        fillComboBox();
        
        // Get ID from session and set it to the text field
   u_id.setText("" + session.uid); 
    u_id.setEditable(false);
    }
    
    public void fillComboBox() {
    try (Connection conn = config.connectDB(); 
         PreparedStatement pst = conn.prepareStatement("SELECT s_name FROM tbl_services");
         ResultSet rs = pst.executeQuery()) {
        
        jComboBox1.removeAllItems(); // This prevents duplicating the list
        jComboBox1.addItem("Select Service");
        
        while(rs.next()) {
            jComboBox1.addItem(rs.getString("s_name"));
        }
    } catch (SQLException e) { 
        System.out.println("Combo Box Error: " + e.getMessage());
    }

    }
private int getServiceId(String serviceName) {
   int id = 0;
    try (Connection conn = config.connectDB();
         PreparedStatement pst = conn.prepareStatement("SELECT s_id FROM tbl_services WHERE s_name = ?")) {
        
        pst.setString(1, serviceName); 
        try (ResultSet rs = pst.executeQuery()) {
            if (rs.next()) {
                id = rs.getInt("s_id"); 
            }
        }
    } catch (SQLException e) {
        System.out.println("Lookup Error: " + e.getMessage());
    }
    return id;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        t_total = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        u_id = new javax.swing.JTextField();
        t_weight = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/adminlogo.png"))); // NOI18N
        jLabel6.setText("jLabel3");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 113, 100));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel7.setText("TRANSACTION FORM");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 310, -1));

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 100));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel1.setText("SERVICE NAME:");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CONFIRM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 220, 60));

        t_total.setEditable(false);
        t_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_totalActionPerformed(evt);
            }
        });
        jPanel7.add(t_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 280, 60));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel12.setText("TOTAL:");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel13.setText("CUSTO... ID");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel14.setText("WEIGHT:");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Services", "Wash & Fold", "Wash", "Dry & Fold", "Ironing Only" }));
        jComboBox1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jComboBox1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 280, 60));

        u_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_idActionPerformed(evt);
            }
        });
        jPanel7.add(u_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 280, 60));

        t_weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_weightActionPerformed(evt);
            }
        });
        t_weight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_weightKeyReleased(evt);
            }
        });
        jPanel7.add(t_weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 280, 60));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 580, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        customerDashboard cd = new customerDashboard();
        cd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     config conf = new config();
    String selectedName = jComboBox1.getSelectedItem().toString();
    
    // 1. Validation
    if (selectedName.equals("Select Service") || t_weight.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please select a service and enter weight!");
        return;
    }

    int actualServiceId = getServiceId(selectedName); 
    String cleanTotal = t_total.getText().replace("₱ ", "").replace(",", "");

    // 2. Use a better way to insert data if your config supports it, 
    // or keep your current one but ensure the values are wrapped in single quotes correctly:
    String sql = "INSERT INTO tbl_laundryorders (u_id, s_id, t_weight, t_total, t_status) "
               + "VALUES ('" + u_id.getText() + "', '" + actualServiceId + "', '" 
               + t_weight.getText() + "', '" + cleanTotal + "', 'Pending')";

    if (conf.insertData(sql) == 1) {
        JOptionPane.showMessageDialog(null, "Order Submitted Successfully!");
        
        // Return to Dashboard
        customerDashboard cd = new customerDashboard();
        cd.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_totalActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // Only trigger the calculation logic when the service changes
        t_weightKeyReleased(null);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void u_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_idActionPerformed

    private void t_weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_weightActionPerformed

    private void t_weightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_weightKeyReleased
      if (jComboBox1.getSelectedIndex() > 0 && !t_weight.getText().trim().isEmpty()) {
        String selectedService = jComboBox1.getSelectedItem().toString();
        
        try (Connection conn = config.connectDB();
             // We use 'COLLATE NOCASE' to ensure it matches even if capitalization differs
             PreparedStatement pst = conn.prepareStatement("SELECT s_price FROM tbl_services WHERE s_name = ? COLLATE NOCASE")) {
            
            pst.setString(1, selectedService);
            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    // 2. Get price from database
                    double price = rs.getDouble("s_price");
                    
                    try {
                        // 3. Convert text to number and calculate
                        double weightValue = Double.parseDouble(t_weight.getText());
                        double totalValue = price * weightValue;
                        
                        // 4. Update the Total field with peso sign
                        t_total.setText("₱ " + String.format("%.2f", totalValue));
                    } catch (NumberFormatException nfe) {
                        // If user types a letter, reset total
                        t_total.setText("₱ 0.00");
                    }
                }
            }
        } catch (SQLException e) {
            System.out.println("Database Error: " + e.getMessage());
        }
    } else {
        // Reset if weight is deleted or "Select Service" is chosen
        t_total.setText("₱ 0.00");
    
    }
    }//GEN-LAST:event_t_weightKeyReleased

    private void jComboBox1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBox1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1AncestorAdded

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        fillComboBox();
    }//GEN-LAST:event_formWindowActivated
public void updateServiceList() {
    try {
        config conf = new config();
        // Clear existing items to avoid duplicates
        jComboBox1.removeAllItems(); 
        
        // Fetch only the names of the services from your table
        String query = "SELECT s_name FROM tbl_services"; 
        ResultSet rs = conf.getData(query);
        
        while(rs.next()) {
            jComboBox1.addItem(rs.getString("s_name"));
        }
    } catch (SQLException e) {
        System.out.println("Error updating services: " + e.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transactionform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transactionform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transactionform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transactionform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transactionform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    public javax.swing.JTextField t_total;
    public javax.swing.JTextField t_weight;
    public javax.swing.JTextField u_id;
    // End of variables declaration//GEN-END:variables
}
