/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;
import config.config; // Import your custom config class
import java.sql.ResultSet; // Import for the database results
import java.sql.SQLException; // Import to handle database errors
import javax.swing.JOptionPane; // Import for the pop-up messages
import Admin.viewtransaction; 
import Admin.servicesform; // Or whichever package they are in
import java.sql.Connection; // Add this line
import java.sql.Statement;  // Add this line too just in case
/**
 *
 * @author jackdaniel
 */
public class edittransaction extends javax.swing.JFrame {

    /**
     * Creates new form edittransaction
     */
    public edittransaction() {
        initComponents();
        fillComboBox();
        
    }
    public void fillComboBox() {
    config conf = new config();
    try {
        // Clear the default items first
        s_id.removeAllItems();
        
        // Fetch only the names from your services table
        ResultSet rs = conf.getData("SELECT s_name FROM tbl_services");
        
        while(rs.next()) {
            // Add each service name to the dropdown automatically
            s_id.addItem(rs.getString("s_name"));
        }
    } catch (SQLException e) {
        System.out.println("Error: " + e.getMessage());
    }
}
    public void calculateTotal() {
   try {
        if (s_id.getSelectedItem() == null || s_id.getSelectedItem().toString().equals("Services")) {
            t_total.setText("0.00");
            return;
        }

        String selectedService = s_id.getSelectedItem().toString();
        
        try (Connection conn = config.connectDB();
             java.sql.Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery("SELECT s_price FROM tbl_services WHERE s_name = '" + selectedService + "'")) {
            
            if (rs.next()) {
                double pricePerKg = rs.getDouble("s_price");
                String weightStr = t_weight.getText().trim();
                
                if (!weightStr.isEmpty()) {
                    try {
                        double weight = Double.parseDouble(weightStr);
                        double total = weight * pricePerKg;
                        t_total.setText(String.format("%.2f", total)); 
                        System.out.println("Total Updated: " + total); // Debugging
                    } catch (NumberFormatException e) {
                        t_total.setText("0.00");
                    }
                } else {
                    t_total.setText("0.00");
                }
            }
        } 
    } catch (SQLException e) {
        System.out.println("Calc Error: " + e.getMessage());
        
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        t_total = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        t_weight = new javax.swing.JTextField();
        u_id = new javax.swing.JTextField();
        t_status = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        s_id = new javax.swing.JComboBox<>();
        t_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/adminlogo.png"))); // NOI18N
        jLabel6.setText("jLabel3");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 113, 100));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setText("EDIT TRANSACTION");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 100));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 180, 60));

        t_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_totalActionPerformed(evt);
            }
        });
        jPanel7.add(t_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 310, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        t_weight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_weightKeyReleased(evt);
            }
        });
        jPanel7.add(t_weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 310, 40));

        u_id.setEditable(false);
        jPanel7.add(u_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 310, 40));

        t_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_statusActionPerformed(evt);
            }
        });
        jPanel7.add(t_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 310, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("CUSTOMER ID:");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("STATUS:");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("TRANSACTION ID:");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        s_id.setEditable(true);
        s_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Services" }));
        s_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_idActionPerformed(evt);
            }
        });
        jPanel7.add(s_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 310, 40));

        t_id.setEditable(false);
        t_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idActionPerformed(evt);
            }
        });
        jPanel7.add(t_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 310, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("SERVICE ID:");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("WEIGHT:");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("TOTAL:");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 580, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        viewtransaction sf = new viewtransaction();
        sf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     config conf = new config();
    String selectedName = s_id.getSelectedItem().toString();
    int actualServiceId = 0;
    
    // Manual lookup to avoid the lock from the getData method
    try (Connection conn = config.connectDB();
         Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery("SELECT s_id FROM tbl_services WHERE s_name = '" + selectedName + "'")) {
        if (rs.next()) {
            actualServiceId = rs.getInt("s_id");
        }
    } catch (SQLException e) {
        System.out.println("Lookup Error: " + e.getMessage());
    }

    String cleanTotal = t_total.getText().replace("₱", "").trim();

    // Now the database is free for the updateData method
    String sql = "UPDATE tbl_laundryorders SET "
               + "s_id = '" + actualServiceId + "', "
               + "t_weight = '" + t_weight.getText() + "', "
               + "t_total = '" + cleanTotal + "', " 
               + "t_status = '" + t_status.getText() + "' "
               + "WHERE t_id = '" + t_id.getText() + "'";

    if (conf.updateData(sql) == 1) {
        JOptionPane.showMessageDialog(null, "Laundry Order Updated!");
        viewtransaction vt = new viewtransaction();
        vt.setVisible(true);
        this.dispose();
        
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_totalActionPerformed

    private void t_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_statusActionPerformed

    private void t_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idActionPerformed

    private void s_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_idActionPerformed
        calculateTotal();
    }//GEN-LAST:event_s_idActionPerformed

    private void t_weightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_weightKeyReleased
        calculateTotal();
    }//GEN-LAST:event_t_weightKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edittransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edittransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edittransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edittransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edittransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    public javax.swing.JComboBox<String> s_id;
    public javax.swing.JTextField t_id;
    public javax.swing.JTextField t_status;
    public javax.swing.JTextField t_total;
    public javax.swing.JTextField t_weight;
    public javax.swing.JTextField u_id;
    // End of variables declaration//GEN-END:variables
}
